version: '3'

services:
  spring:
    container_name: spring
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8086:8080"
    networks:
      - web

networks:
  web:
    external: true
