version: '3'

services:
  finance:
    container_name: finance
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8086:8080"
    networks:
      - web

networks:
  web:
    external: true
